server:
  port: 8080

spring:
  profiles:
    active: @activatedProperties@
  datasource:
    username: lingx
    password: Lingx_2019
    url: jdbc:mysql://192.168.56.10/spring_shiro?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:

      #初始化时建立物理连接的个数
      initial-size: 5
      #最小连接池数量
      min-idle: 5
      #最大连接池数量 maxIdle已经不再使用
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: select 'x'
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: true
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      #当数据库抛出不可恢复的异常时,抛弃该连接
      #exception-sorter: true
      #是否缓存preparedStatement,mysql5.5+建议开启
      #spring.datasource.druid.pool-prepared-statements=true
      #当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 20
      #配置扩展插件
      filters: stat,wall
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: true;druid.stat.slowSqlMillis=500
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true


  # 当出现 404 错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  #不要为工程中的资源文件建立映射.
  resources:
    add-mappings: false

  thymeleaf:
    cache: false #禁用模板引擎编译的缓存结果。由热部署来实现，更改代码后，使用Ctrl+F9(IDEA)更新
    mode: LEGACYHTML5 #避免thymeleaf对html文件的严格校验（如检查标签必须对称等）

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000 #超时时间
    lettuce:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    password:


mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.lx.study.springshiro.entity
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml


# 分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSqcl
  page-size-zero: true



name: dev-zhangsan